#!/bin/env bash

while true; do
  mkdir $HOME/.coords_mine
  clear
  printf "AVISO: Todas as TPs salvas no automatico são escritas no final do arquivo, caso você queira organizar, você pode escolher a opção: [2] - Gerenciar minhas coordenadas OU abrir seu editor de texto preferido em: $EDITOR (Nome do arquivo) para organizar tudo manualmente!!!"

  printf "\n\nO que você deseja fazer?:\n\n"
  printf "[01] - Criar um novo arquivo de texto\n"
  printf "[02] - Salvar coordenadas\n"
  printf "[03] - Gerenciar minhas coordenadas\n"
  printf "[04] - Limpar tela\n"
  printf "[05] - Voltar\n\n"
  printf "Dica: Para sair do script você pode pressionar: Ctrl+C\n\n"
  read OPC1

  # Conditions
  if [ $OPC1 == '1' ] || [ $OPC1 == '01' ] ; then
    clear
    cd $HOME/.coords_mine && printf "Digite o nome do Arquivo (Evite espaços e acentuações):\n\n"
    read FILE_NAME
    touch $HOME/."$FILE_NAME"

  elif [ $OPC1 == '2' ] || [ $OPC1 == '02' ] ; then
    printf "\n\nCole a coordenada aqui e coloque o nome dela: (Ex: X Y Z - Minha casa)\n\n"
    read COORD
    cd $HOME/.coords_mine && ls && printf "\n\n Agora digite o nome do arquivo que queira salvar:\n\n"
    read FILE_NAME1
    cd $HOME/.coords_mine && printf "\n\n/tp $COORD >> $FILE_NAME1"

  elif [ $OPC1 == '3' ] || [ $OPC1 == '03' ] ; then
    cd $HOME/.coords_mine && clear && ls && printf "\nEscolha qual arquivo de texto você quer gerenciar:\n\n"
    read FILE_NAME2
    cd $HOME/.coords_mine && $EDITOR $FILE_NAME2

  elif [ $OPC1 == '4' ] || [ $OPC1 == '04' ] ; then
    clear

  elif [ $OPC1 == '5' ] || [ $OPC1 == '05' ] ; then
    $HOME/.local/bin/minec
  fi
done

