#!/bin/python3

# Imports
import os
import random

# VAR
var1 = '-'
var2 = ''
result = var1 , var2
result1 = random.choice(result)

# LOCATION
X = ''
Y = ''
Z = ''
coord1 = X
coord2 = Y
coord3 = Z

coord1 = random.randint(1 , 9999)
coord2 = random.randint(1 , 99)
coord3 = random.randint(1 , 999999)

os.system('clear')
print(f'X: {result1}{coord1} / Y: {coord2} / Z: {coord3}')
print(f'\n/tp {result1}{coord1} {coord2} {coord3}')

