#!/bin/env bash

clear
printf "
 ██████╗ ██████╗  ██████╗ ██████╗ ██████╗ ██╗███╗   ██╗ █████╗ ████████╗███████╗███████╗
██╔════╝██╔═══██╗██╔═══██╗██╔══██╗██╔══██╗██║████╗  ██║██╔══██╗╚══██╔══╝██╔════╝██╔════╝
██║     ██║   ██║██║   ██║██████╔╝██║  ██║██║██╔██╗ ██║███████║   ██║   █████╗  ███████╗
██║     ██║   ██║██║   ██║██╔══██╗██║  ██║██║██║╚██╗██║██╔══██║   ██║   ██╔══╝  ╚════██║
╚██████╗╚██████╔╝╚██████╔╝██║  ██║██████╔╝██║██║ ╚████║██║  ██║   ██║   ███████╗███████║
 ╚═════╝ ╚═════╝  ╚═════╝ ╚═╝  ╚═╝╚═════╝ ╚═╝╚═╝  ╚═══╝╚═╝  ╚═╝   ╚═╝   ╚══════╝╚══════╝
                                                                                         \n\n"
read -p 'Press enter to continue...'
while true; do
  clear
  printf "AVISO: O código pode spwanar VOCÊ em QUALQUER LUGAR do minecraft, são números aleatorios imprimidos na tela, ou seja... ninguém sabe onde você sera dropado! RECOMENDADO: Se você for usar esse programa, NÃO leve itens importantes, leve o basico você CORRE O RISCO de ser dropado direto a morte 

OBJETIVO DO PROGRAMA: O objetivo do programa é para você que quer viajar no MEGA MUNDO DO MINECRAFT aleatoriamente para pode farmar!!!

VOCÊ PODE...: Cair dentro de uma pedra e ficar bugado, nesse caso você pode teleportar para um local seguro que você conheca, ou quebrar a pedra com a picareta! 
VOCÊ PODE...: Cair de uma altura muito alta e morrer, você pode levar um balde de aguá e tentar no TIME (TEMPO) certo soltar a água para amortecer sua queda! 
VOCÊ PODE...: Cair em algum lugar bugado e não ter como quebrar o bloco e nem se teleportar, ou seja você pode morrer (RECOMENDADO: Levar itens necessários)!\n\n"
  
  printf "[01] - Coordenada aleatoria\n"
  printf "[02] - Gerenciar coordenadas\n\n"
  printf "Dica: Para sair do script pressione: Ctrl+C\n\n"
  read OPC

  if [ $OPC == '1' ] || [ $OPC == '01' ] ; then
    printf "\n\n"
    mine_coordenates
    printf "\nDeseja salvar?\n\n"
    printf "1 - Sim\n"
    printf "2 - Não\n\n"
    read SAVE
    printf "\n\n"
  elif [ $OPC == '2' ] || [ $OPC == '02' ] ; then
    printf "\n\n"
    manager_save
  fi
 
  if [ $SAVE == '1' ] || [ $SAVE == '01' ] ; then
    auto_save 
    read -p 'Press enter to continue...'
  
  elif [ $SAVE != '1' ] || [ $SAVE == '01' ] ; then 
    continue
  fi
done

